name: flutter_restaurant
description: A new Flutter restaurant application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.1+3

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  cupertino_icons: ^1.0.8
  get_it: ^8.0.3
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  dio: ^5.4.3+1
  http: ^1.4.0
  image_picker: ^1.1.2
  pin_code_fields: ^8.0.1
  google_maps_flutter_web: ^0.5.7
  google_maps_flutter: ^2.6.1
#  flutter_google_places: ^0.3.0
#  flutter_google_places: ^0.3.0
  flutter_google_places_hoc081098:
    git:
      url: https://github.com/Sobitandra/flutter_google_places_hoc081098.git
  geocoding: ^3.0.0
  geolocator: ^14.0.0
  shimmer_animation:
  url_launcher: ^6.3.1
  webview_flutter: ^4.11.0
  webview_flutter_android: ^4.4.2
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^19.1.0
  path_provider: ^2.1.5
  connectivity_plus: ^6.1.4
  url_strategy: ^0.3.0
  universal_html: ^2.2.4
  image: ^4.1.7
  flutter_widget_from_html_core: ^0.8.5+3
  country_code_picker: ^3.0.0
  flutter_typeahead: ^5.2.0
  fwfh_selectable_text: ^0.8.3+1
  circular_countdown_timer: ^0.2.3
  timezone: ^0.10.1
  marquee: ^2.3.0
  flutter_inappwebview: ^6.1.5
  google_sign_in: ^6.2.1
  dotted_border: ^2.1.0
  share_plus: ^11.0.0
  expandable_bottom_sheet: ^1.1.1+1
  scroll_to_index: ^3.0.1
#  google_maps_webservice: ^0.0.19
  photo_view: ^0.15.0
  cached_network_image: ^3.4.1
  just_the_tooltip: ^0.0.12
  sign_in_with_apple: ^7.0.1
  go_router: ^15.1.1
  firebase_auth: ^5.5.3
  flutter_svg: ^2.1.0
  flutter_staggered_grid_view: ^0.7.0
  dropdown_search: ^5.0.6
  animated_custom_dropdown: ^3.1.1
  dropdown_button2: ^2.3.9
  carousel_slider: ^5.0.0
  drift: ^2.19.0
  drift_flutter: ^0.1.0
  google_api_headers: ^4.4.5


  collection: any
  iconsax: ^0.0.8
  pusher_channels_flutter: ^2.4.0
  custom_info_window: ^1.0.1
  readmore: ^3.0.0
  vibration: ^3.1.3
  shimmer:
  change_app_package_name: ^1.5.0

#  app_links: ^6.4.0


dependency_overrides:
#  webview_flutter_android: 3.16.1

dev_dependencies:
  flutter_lints: ^5.0.0
  fwfh_text_style: ^2.23.8
  drift_dev: ^2.19.0
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
    android: true
    ios: true
    image_path: "assets/icon/pco.png"
    min_sdk_android: 21 # android min sdk min:16, default 21


flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/image/
    - assets/svg/
    - assets/language/
    - assets/json/
    - assets/payment/
    - assets/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/NunitoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/NunitoSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/NunitoSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NunitoSans-Bold.ttf
          weight: 700

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400